"""Remove offset column from User

Revision ID: d290afcf2f0e
Revises: c487e3664225
Create Date: 2025-08-08 15:02:27.051355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd290afcf2f0e'
down_revision = 'c487e3664225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('offset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
